"""termin realizacji zamowienia

Revision ID: 33c9f2ce47eb
Revises: 59680847d491
Create Date: 2025-03-18 07:52:27.970286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c9f2ce47eb'
down_revision: Union[str, None] = '59680847d491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term', sa.String(), nullable=True, server_default=""))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('term')

    # ### end Alembic commands ###
