"""id_zamowienia

Revision ID: 5574e8cd7a25
Revises: 8e87bcf3e617
Create Date: 2026-01-31 10:08:01.189479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5574e8cd7a25'
down_revision: Union[str, None] = '8e87bcf3e617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('string_order_id', sa.String(), nullable=True))
        batch_op.alter_column("string_order_id", existing_type=sa.String(), nullable=True, unique=True)


    reservations_table = sa.Table(
        'reservations',
        sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('date', sa.DateTime()),
        sa.Column('string_order_id', sa.String())
    )

    connection = op.get_bind()

    results = connection.execute(
        sa.select(reservations_table.c.id, reservations_table.c.date, reservations_table.c.string_order_id)
    ).all()
    i = 0
    for row in results:
        if row.date.year == 2025:
            generated_value = str(row.id) + '/25'
        else: 
            i+=1
            generated_value = str(i) + '/26'

        

        connection.execute(
            reservations_table.update().
            where(reservations_table.c.id == row.id).
            values(string_order_id=generated_value)
        )
     

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('string_order_id')

    # ### end Alembic commands ###
