"""public adnotations column

Revision ID: 59680847d491
Revises: 9d5ba8f68131
Create Date: 2025-03-11 10:44:06.443533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59680847d491'
down_revision: Union[str, None] = '9d5ba8f68131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adnotation_pub', sa.String(), nullable=True, server_default=""))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('adnotation_pub')

    # ### end Alembic commands ###
