"""banki_i_dostawa

Revision ID: 8e87bcf3e617
Revises: 33c9f2ce47eb
Create Date: 2025-05-17 16:10:11.487810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import false


# revision identifiers, used by Alembic.
revision: str = '8e87bcf3e617'
down_revision: Union[str, None] = '33c9f2ce47eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery', sa.Boolean(), nullable=True,  server_default = false()))
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True, server_default = "Santander"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('delivery')

    # ### end Alembic commands ###
