"""klienci do potwierdzenia

Revision ID: 9d5ba8f68131
Revises: aaadf09fd8d6
Create Date: 2025-03-09 15:01:04.752617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5ba8f68131'
down_revision: Union[str, None] = 'aaadf09fd8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('company_name')
        batch_op.drop_column('adress')

    # ### end Alembic commands ###
