"""serio_unique

Revision ID: aaadf09fd8d6
Revises: 7d1baa5031df
Create Date: 2025-02-26 21:21:52.741017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaadf09fd8d6'
down_revision: Union[str, None] = '7d1baa5031df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_brand_name", ['name'])

    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_colour_name", ['name'])

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_model_namehash", ['namehash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint("unique_model_namehash", type_='unique')

    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.drop_constraint("unique_colour_name", type_='unique')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint("unique_brand_name", type_='unique')

    # ### end Alembic commands ###
