"""rewizja4

Revision ID: d314ba969295
Revises: 
Create Date: 2025-02-22 23:16:10.807315

"""
from typing import Sequence, Union
from migrate import UniqueConstraint
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd314ba969295'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("models") as batch_op:
        batch_op.add_column(Column("namehash", sa.String(), nullable=False))
        op.create_unique_constraint("unique_model", 'models', ['namehash'])
    
    with op.batch_alter_table("brands") as batch_op:
        batch_op.create_unique_constraint("unique_brand", 'brands', ['namehash'])
    
    with op.batch_alter_table("some_table") as batch_op:
        batch_op.add_column("models", Column("namehash", sa.String(), nullable=False))
        op.create_unique_constraint("unique_model", 'models', ['namehash'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_brand_name", 'models', type_='unique')
    op.drop_column('models', 'namehash')
    op.drop_constraint("unique_colour_name", 'colours', type_='unique')
    op.drop_constraint("unique_model", 'brands', type_='unique')
    # ### end Alembic commands ###
